Добавил наставника
htmlacademy-htmlcss/2178613-gllacy-35 pull request #1
Opened 2022-09-25 22:39 UTC by nikolai-skor

2022-09-26 01:29 UTC, Dima-Dim requested changes

2022-09-26 01:29 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`(https://htmlacademy.ru/profile/dima).
Сейчас это выглядит вот так:
https://github.com/htmlacademy-htmlcss/2178613-gllacy-35/blob/ea96273e027bcf04809d2d496350a45d62fb0f1a/Readme.md
Нужно немного поправить чтобы ссылкой были имя и фамилия.

2022-09-26 07:36 UTC, nikolai-skor commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`(https://htmlacademy.ru/profile/dima).
Исправил, исходя из логики. Приветствую, приятно познакомиться.

2022-09-26 14:54 UTC, merged

2022-09-27 01:30 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`(https://htmlacademy.ru/profile/dima).
Отлично, логика это то, что нужно! И взаимно ;)